#if just
export concurrently_colors := "blue,green,yellow,magenta,cyan,white"

help:
    just --list

setup:
    npm clean-install #if (or node squint)

dev:
    npm run dev #if (or node astro)
    typst watch main.typ #if typst
    gleam run -m lustre/dev start #if (and gleam lustre)

build:
    typst compile main.typ #if typst

run:
    gleam run #if (and just gleam)

open cmd="":
    #!/usr/bin/env bash
    url="http://localhost:8080"

    if [[ -n "{{ cmd }}" ]]; then
        {{ cmd }} "$url"
    elif command -v xdg-open &> /dev/null; then
        xdg-open "$url"
    elif command -v open &> /dev/null; then
        open "$url"
    else
        echo "No suitable cmd found. Please install xdg-open or open."
        exit 1
    fi

test:
    gleam test #if (and just gleam)

all:
    concurrently \
    --names "test,lint" \
    --prefix-colors ${concurrently_colors} \
        "just test" \
        "just lint"
#endif just
