#if just
export concurrently_colors := "blue,green,yellow,magenta,cyan,white"

help:
    just --list

setup:
    npm clean-install #if (or node squint)

dev:
    npm run dev #if (or node astro)
    gleam run -m lustre/dev start #if (and gleam lustre)

run:
    gleam run #if (and just gleam)

test:
    gleam test #if (and just gleam)

all:
    concurrently \
    --names "test,lint" \
    --prefix-colors ${concurrently_colors} \
        "just test" \
        "just lint"
#endif just
